image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: 'hugo server --baseUrl $(gp url 1313) --appendPort=false --buildDrafts'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
  - port: 1313
    onOpen: open-preview

vscode:
  extensions:
    - "streetsidesoftware.code-spell-checker"